"""layer owner

Revision ID: 0e2fb3550e5b
Revises: 6f557c727b52
Create Date: 2023-01-17 15:59:02.911021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2fb3550e5b'
down_revision = '6f557c727b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layer_owner', sa.Integer(), nullable=True))
        batch_op.drop_constraint('layer_layer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['layer_owner'], ['id'])
        batch_op.drop_column('layer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('layer_layer_id_fkey', 'user', ['layer_id'], ['id'])
        batch_op.drop_column('layer_owner')

    # ### end Alembic commands ###
