"""product no

Revision ID: 63777f7291b1
Revises: 0e2fb3550e5b
Create Date: 2023-01-17 20:38:23.362943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63777f7291b1'
down_revision = '0e2fb3550e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_no', sa.Integer(), nullable=False))
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('project_no')

    # ### end Alembic commands ###
