"""Data name remove

Revision ID: 9723bf5c746d
Revises: 7c6e30eb33e4
Create Date: 2023-01-17 23:25:06.208832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9723bf5c746d'
down_revision = '7c6e30eb33e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
